export const GET_PEOPLE_DATA = "GET_PEOPLE_DATA";
export const SET_PEOPLE_DATA = "SET_PEOPLE_DATA";
export const ERROR_PEOPLE_DATA = "ERROR_PEOPLE_DATA";
export const CHANGE_FILTER_PEOPLE = "CHANGE_FILTER_PEOPLE";
